# Adds a "Sponsor" button to the repo header on GitHub.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: dcherrera
custom:
  - https://teamide.dev/support
