"""
Embed firmware-bundled assets as C arrays:
  - src/embedded/firmware_home.lua  -> lib/plugin/firmware_home_lua.h
  - sdcard/fonts/Ubuntu/Ubuntu-12-Regular.cfont -> lib/font/embedded_boot_font.h

Runs as a PlatformIO pre-script before compilation. Idempotent: regenerates
each header only when the source has changed, so unchanged builds skip
recompiling files that include them.
"""

import os
import sys

Import("env")  # noqa: F821 — provided by PlatformIO

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821


def emit_c_array(src_path: str, dst_path: str, var_name: str, label: str) -> None:
    with open(src_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append("/* AUTO-GENERATED by tools/embed_assets.py — do not edit. */")
    lines.append(f"/* Source: {label} */")
    lines.append("#pragma once")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"static const unsigned char {var_name}[] = {{")

    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        row = "    " + ", ".join(f"0x{b:02x}" for b in chunk) + ","
        lines.append(row)

    lines.append("};")
    lines.append(f"static const uint32_t {var_name}_len = {len(data)};")
    lines.append("")

    new_text = "\n".join(lines)

    # Skip rewrite when content is unchanged — preserves mtime, avoids needless rebuilds.
    if os.path.exists(dst_path):
        with open(dst_path, "r") as f:
            if f.read() == new_text:
                return

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w") as f:
        f.write(new_text)
    print(f"[embed_assets] {os.path.relpath(src_path, PROJECT_DIR)} -> "
          f"{os.path.relpath(dst_path, PROJECT_DIR)} ({len(data)} bytes)")


ASSETS = [
    {
        "src": os.path.join(PROJECT_DIR, "src", "embedded", "firmware_home.lua"),
        "dst": os.path.join(PROJECT_DIR, "lib", "plugin", "firmware_home_lua.h"),
        "var": "firmware_home_lua",
        "label": "src/embedded/firmware_home.lua",
    },
    {
        "src": os.path.join(PROJECT_DIR, "sdcard", "fonts", "Ubuntu", "Ubuntu-12-Regular.cfont"),
        "dst": os.path.join(PROJECT_DIR, "lib", "font", "embedded_boot_font.h"),
        "var": "embedded_boot_font",
        "label": "sdcard/fonts/Ubuntu/Ubuntu-12-Regular.cfont",
    },
]

for a in ASSETS:
    if not os.path.exists(a["src"]):
        print(f"[embed_assets] ERROR: source not found: {a['src']}", file=sys.stderr)
        env.Exit(1)  # noqa: F821
    emit_c_array(a["src"], a["dst"], a["var"], a["label"])
